<?php
/**
 * ACF Local Field Groups
 * Registers all ACF field groups programmatically so they work without the DB.
 *
 * @package bluu-interactive
 */

defined( 'ABSPATH' ) || exit;

if ( ! function_exists( 'acf_add_local_field_group' ) ) {
    return;
}

// ── HOME PAGE ──────────────────────────────────────────────────────────────────
acf_add_local_field_group( array(
    'key'      => 'group_home_hero',
    'title'    => 'Home: Hero Section',
    'fields'   => array(
        array(
            'key'           => 'field_hero_badge',
            'label'         => 'Badge Text',
            'name'          => 'hero_badge',
            'type'          => 'text',
            'default_value' => 'Anti-Fragmentation Agency',
        ),
        array(
            'key'           => 'field_hero_headline',
            'label'         => 'Headline',
            'name'          => 'hero_headline',
            'type'          => 'text',
            'default_value' => 'Stop Managing Vendors. Start Closing Revenue.',
        ),
        array(
            'key'           => 'field_hero_subheadline',
            'label'         => 'Subheadline',
            'name'          => 'hero_subheadline',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Bluu Interactive replaces your web developer, SEO agency, and sales content team with one synchronized engine that drives traffic, converts leads, and closes deals.',
        ),
        array(
            'key'           => 'field_hero_cta_primary_text',
            'label'         => 'Primary CTA Text',
            'name'          => 'hero_cta_primary_text',
            'type'          => 'text',
            'default_value' => 'Book a Discovery Call',
        ),
        array(
            'key'           => 'field_hero_cta_primary_url',
            'label'         => 'Primary CTA URL',
            'name'          => 'hero_cta_primary_url',
            'type'          => 'url',
            'default_value' => '/contact',
        ),
        array(
            'key'           => 'field_hero_cta_secondary_text',
            'label'         => 'Secondary CTA Text',
            'name'          => 'hero_cta_secondary_text',
            'type'          => 'text',
            'default_value' => 'See How It Works',
        ),
        array(
            'key'           => 'field_hero_cta_secondary_url',
            'label'         => 'Secondary CTA URL',
            'name'          => 'hero_cta_secondary_url',
            'type'          => 'url',
            'default_value' => '#pillars',
        ),
        array(
            'key'        => 'field_hero_stats',
            'label'      => 'Stats',
            'name'       => 'hero_stats',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 6,
            'layout'     => 'table',
            'sub_fields' => array(
                array(
                    'key'           => 'field_hero_stat_number',
                    'label'         => 'Number',
                    'name'          => 'stat_number',
                    'type'          => 'text',
                    'default_value' => '',
                    'column_width'  => '',
                ),
                array(
                    'key'           => 'field_hero_stat_label',
                    'label'         => 'Label',
                    'name'          => 'stat_label',
                    'type'          => 'text',
                    'default_value' => '',
                    'column_width'  => '',
                ),
            ),
        ),
    ),
    'location' => array( array( array(
        'param'    => 'page_type',
        'operator' => '==',
        'value'    => 'front_page',
    ) ) ),
    'menu_order'            => 10,
    'position'              => 'normal',
    'style'                 => 'default',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'active'                => true,
) );

acf_add_local_field_group( array(
    'key'    => 'group_home_problem',
    'title'  => 'Home: Problem Section',
    'fields' => array(
        array(
            'key'           => 'field_problem_badge',
            'label'         => 'Badge',
            'name'          => 'problem_badge',
            'type'          => 'text',
            'default_value' => 'The Problem',
        ),
        array(
            'key'           => 'field_problem_headline',
            'label'         => 'Headline',
            'name'          => 'problem_headline',
            'type'          => 'text',
            'default_value' => 'Fragmentation Is Costing You Revenue',
        ),
        array(
            'key'           => 'field_problem_body',
            'label'         => 'Body',
            'name'          => 'problem_body',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Most B2B companies are paying 3–5 vendors who never talk to each other. The result: misaligned messaging, stalled pipeline, and a digital presence that doesn\'t convert.',
        ),
        array(
            'key'        => 'field_problem_items',
            'label'      => 'Problem Items',
            'name'       => 'problem_items',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 6,
            'layout'     => 'block',
            'sub_fields' => array(
                array(
                    'key'           => 'field_problem_item_icon',
                    'label'         => 'Icon (SVG name)',
                    'name'          => 'icon',
                    'type'          => 'text',
                    'default_value' => 'x-circle',
                ),
                array(
                    'key'           => 'field_problem_item_title',
                    'label'         => 'Title',
                    'name'          => 'title',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_problem_item_description',
                    'label'         => 'Description',
                    'name'          => 'description',
                    'type'          => 'textarea',
                    'rows'          => 3,
                    'default_value' => '',
                ),
            ),
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_type',
        'operator' => '==',
        'value'    => 'front_page',
    ) ) ),
    'menu_order' => 20,
    'active'     => true,
) );

acf_add_local_field_group( array(
    'key'    => 'group_home_solution',
    'title'  => 'Home: Solution / Pillars Section',
    'fields' => array(
        array(
            'key'           => 'field_solution_badge',
            'label'         => 'Solution Badge',
            'name'          => 'solution_badge',
            'type'          => 'text',
            'default_value' => 'The Solution',
        ),
        array(
            'key'           => 'field_solution_headline',
            'label'         => 'Solution Headline',
            'name'          => 'solution_headline',
            'type'          => 'text',
            'default_value' => 'One Team. Three Engines. Total Growth.',
        ),
        array(
            'key'           => 'field_solution_body',
            'label'         => 'Solution Body',
            'name'          => 'solution_body',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Bluu Interactive unifies web infrastructure, authority content, and sales assets under one synchronized strategy — so every touchpoint works together.',
        ),
        array(
            'key'        => 'field_pillars',
            'label'      => 'Pillars',
            'name'       => 'pillars',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 3,
            'layout'     => 'block',
            'sub_fields' => array(
                array(
                    'key'           => 'field_pillar_icon',
                    'label'         => 'Icon Name',
                    'name'          => 'pillar_icon',
                    'type'          => 'text',
                    'default_value' => 'server',
                ),
                array(
                    'key'           => 'field_pillar_label',
                    'label'         => 'Label Chip',
                    'name'          => 'pillar_label',
                    'type'          => 'text',
                    'default_value' => 'Pillar 1',
                ),
                array(
                    'key'           => 'field_pillar_title',
                    'label'         => 'Title',
                    'name'          => 'pillar_title',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_pillar_description',
                    'label'         => 'Description',
                    'name'          => 'pillar_description',
                    'type'          => 'textarea',
                    'rows'          => 3,
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_pillar_feature_1',
                    'label'         => 'Feature 1',
                    'name'          => 'pillar_feature_1',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_pillar_feature_2',
                    'label'         => 'Feature 2',
                    'name'          => 'pillar_feature_2',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_pillar_feature_3',
                    'label'         => 'Feature 3',
                    'name'          => 'pillar_feature_3',
                    'type'          => 'text',
                    'default_value' => '',
                ),
            ),
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_type',
        'operator' => '==',
        'value'    => 'front_page',
    ) ) ),
    'menu_order' => 30,
    'active'     => true,
) );

acf_add_local_field_group( array(
    'key'    => 'group_home_icp',
    'title'  => 'Home: ICP / Who We Serve Section',
    'fields' => array(
        array(
            'key'           => 'field_icp_badge',
            'label'         => 'Badge',
            'name'          => 'icp_badge',
            'type'          => 'text',
            'default_value' => 'Who We Serve',
        ),
        array(
            'key'           => 'field_icp_headline',
            'label'         => 'Headline',
            'name'          => 'icp_headline',
            'type'          => 'text',
            'default_value' => 'Built for $2M–$50M B2B Companies',
        ),
        array(
            'key'           => 'field_icp_body',
            'label'         => 'Body',
            'name'          => 'icp_body',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'We focus exclusively on industries where expertise, trust, and precision are non-negotiable. If your buyers demand authority, we\'re built for you.',
        ),
        array(
            'key'        => 'field_icp_verticals',
            'label'      => 'Verticals',
            'name'       => 'icp_verticals',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 8,
            'layout'     => 'block',
            'sub_fields' => array(
                array(
                    'key'           => 'field_icp_vertical_icon',
                    'label'         => 'Icon',
                    'name'          => 'icon',
                    'type'          => 'text',
                    'default_value' => 'briefcase',
                ),
                array(
                    'key'           => 'field_icp_vertical_title',
                    'label'         => 'Title',
                    'name'          => 'title',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_icp_vertical_description',
                    'label'         => 'Description',
                    'name'          => 'description',
                    'type'          => 'textarea',
                    'rows'          => 3,
                    'default_value' => '',
                ),
            ),
        ),
        array(
            'key'           => 'field_home_cta_headline',
            'label'         => 'CTA Headline',
            'name'          => 'home_cta_headline',
            'type'          => 'text',
            'default_value' => 'Ready to Replace Fragmentation With Growth?',
        ),
        array(
            'key'           => 'field_home_cta_body',
            'label'         => 'CTA Body',
            'name'          => 'home_cta_body',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Book a 30-minute Discovery Call. No pitch. Just an honest conversation about your current stack and where the gaps are.',
        ),
        array(
            'key'           => 'field_home_cta_button_text',
            'label'         => 'CTA Button Text',
            'name'          => 'home_cta_button_text',
            'type'          => 'text',
            'default_value' => 'Book a Discovery Call',
        ),
        array(
            'key'           => 'field_home_cta_button_url',
            'label'         => 'CTA Button URL',
            'name'          => 'home_cta_button_url',
            'type'          => 'url',
            'default_value' => '/contact',
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_type',
        'operator' => '==',
        'value'    => 'front_page',
    ) ) ),
    'menu_order' => 40,
    'active'     => true,
) );

// ── PRICING PAGE ───────────────────────────────────────────────────────────────
acf_add_local_field_group( array(
    'key'    => 'group_pricing',
    'title'  => 'Pricing Page Fields',
    'fields' => array(
        array(
            'key'           => 'field_pricing_hero_headline',
            'label'         => 'Hero Headline',
            'name'          => 'pricing_hero_headline',
            'type'          => 'text',
            'default_value' => 'Transparent, All-Inclusive Pricing',
        ),
        array(
            'key'           => 'field_pricing_hero_subheadline',
            'label'         => 'Hero Subheadline',
            'name'          => 'pricing_hero_subheadline',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'No retainer games. No surprise invoices. One subscription that covers everything your growth engine needs.',
        ),
        array(
            'key'        => 'field_pricing_tiers',
            'label'      => 'Pricing Tiers',
            'name'       => 'pricing_tiers',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 5,
            'layout'     => 'block',
            'sub_fields' => array(
                array(
                    'key'           => 'field_tier_badge',
                    'label'         => 'Badge',
                    'name'          => 'tier_badge',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_tier_name',
                    'label'         => 'Tier Name',
                    'name'          => 'tier_name',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_tier_price',
                    'label'         => 'Price',
                    'name'          => 'tier_price',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_tier_price_suffix',
                    'label'         => 'Price Suffix',
                    'name'          => 'tier_price_suffix',
                    'type'          => 'text',
                    'default_value' => '/month',
                ),
                array(
                    'key'           => 'field_tier_tagline',
                    'label'         => 'Tagline',
                    'name'          => 'tier_tagline',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_tier_features',
                    'label'         => 'Features (one per line)',
                    'name'          => 'tier_features',
                    'type'          => 'textarea',
                    'rows'          => 6,
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_tier_cta_text',
                    'label'         => 'CTA Text',
                    'name'          => 'tier_cta_text',
                    'type'          => 'text',
                    'default_value' => 'Get Started',
                ),
                array(
                    'key'           => 'field_tier_cta_url',
                    'label'         => 'CTA URL',
                    'name'          => 'tier_cta_url',
                    'type'          => 'url',
                    'default_value' => '/contact',
                ),
                array(
                    'key'           => 'field_tier_is_featured',
                    'label'         => 'Is Featured (Most Popular)?',
                    'name'          => 'tier_is_featured',
                    'type'          => 'true_false',
                    'default_value' => 0,
                ),
                array(
                    'key'           => 'field_tier_note',
                    'label'         => 'Footer Note',
                    'name'          => 'tier_note',
                    'type'          => 'text',
                    'default_value' => '',
                ),
            ),
        ),
        array(
            'key'        => 'field_pricing_faq',
            'label'      => 'FAQ Items',
            'name'       => 'pricing_faq',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 20,
            'layout'     => 'block',
            'sub_fields' => array(
                array(
                    'key'           => 'field_faq_question',
                    'label'         => 'Question',
                    'name'          => 'question',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_faq_answer',
                    'label'         => 'Answer',
                    'name'          => 'answer',
                    'type'          => 'textarea',
                    'rows'          => 4,
                    'default_value' => '',
                ),
            ),
        ),
        array(
            'key'           => 'field_pricing_bottom_cta_headline',
            'label'         => 'Bottom CTA Headline',
            'name'          => 'pricing_bottom_cta_headline',
            'type'          => 'text',
            'default_value' => 'Not Sure Which Plan Fits?',
        ),
        array(
            'key'           => 'field_pricing_bottom_cta_body',
            'label'         => 'Bottom CTA Body',
            'name'          => 'pricing_bottom_cta_body',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Let\'s talk. A 30-minute Discovery Call is free and commitment-free. We\'ll tell you exactly which plan — if any — makes sense for your stage.',
        ),
        array(
            'key'           => 'field_pricing_bottom_cta_button_text',
            'label'         => 'Bottom CTA Button Text',
            'name'          => 'pricing_bottom_cta_button_text',
            'type'          => 'text',
            'default_value' => 'Book a Discovery Call',
        ),
        array(
            'key'           => 'field_pricing_bottom_cta_button_url',
            'label'         => 'Bottom CTA Button URL',
            'name'          => 'pricing_bottom_cta_button_url',
            'type'          => 'url',
            'default_value' => '/contact',
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_template',
        'operator' => '==',
        'value'    => 'page-pricing.php',
    ) ) ),
    'menu_order' => 10,
    'active'     => true,
) );

// ── INDUSTRIES PAGE ────────────────────────────────────────────────────────────
acf_add_local_field_group( array(
    'key'    => 'group_industries',
    'title'  => 'Industries Page Fields',
    'fields' => array(
        array(
            'key'           => 'field_industries_hero_headline',
            'label'         => 'Hero Headline',
            'name'          => 'industries_hero_headline',
            'type'          => 'text',
            'default_value' => 'Built for Industries Where Trust Is Non-Negotiable',
        ),
        array(
            'key'           => 'field_industries_hero_subheadline',
            'label'         => 'Hero Subheadline',
            'name'          => 'industries_hero_subheadline',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'We don\'t work in every industry. We go deep in four — where our expertise creates an unfair competitive advantage for our clients.',
        ),
        array(
            'key'        => 'field_industries',
            'label'      => 'Industries',
            'name'       => 'industries',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 8,
            'layout'     => 'block',
            'sub_fields' => array(
                array(
                    'key'           => 'field_industry_icon',
                    'label'         => 'Icon',
                    'name'          => 'industry_icon',
                    'type'          => 'text',
                    'default_value' => 'briefcase',
                ),
                array(
                    'key'           => 'field_industry_name',
                    'label'         => 'Industry Name',
                    'name'          => 'industry_name',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_industry_tagline',
                    'label'         => 'Tagline',
                    'name'          => 'industry_tagline',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_industry_challenge',
                    'label'         => 'Challenge',
                    'name'          => 'industry_challenge',
                    'type'          => 'textarea',
                    'rows'          => 3,
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_industry_solution',
                    'label'         => 'Solution',
                    'name'          => 'industry_solution',
                    'type'          => 'textarea',
                    'rows'          => 3,
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_industry_stat_number',
                    'label'         => 'Stat Number',
                    'name'          => 'industry_stat_number',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_industry_stat_label',
                    'label'         => 'Stat Label',
                    'name'          => 'industry_stat_label',
                    'type'          => 'text',
                    'default_value' => '',
                ),
            ),
        ),
        array(
            'key'           => 'field_industries_bottom_cta_headline',
            'label'         => 'Bottom CTA Headline',
            'name'          => 'industries_bottom_cta_headline',
            'type'          => 'text',
            'default_value' => 'Your Industry. Your Rules. Our Engine.',
        ),
        array(
            'key'           => 'field_industries_bottom_cta_body',
            'label'         => 'Bottom CTA Body',
            'name'          => 'industries_bottom_cta_body',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'We only take on clients we know we can win for. Let\'s find out if we\'re the right fit.',
        ),
        array(
            'key'           => 'field_industries_bottom_cta_button_text',
            'label'         => 'Bottom CTA Button Text',
            'name'          => 'industries_bottom_cta_button_text',
            'type'          => 'text',
            'default_value' => 'Book a Discovery Call',
        ),
        array(
            'key'           => 'field_industries_bottom_cta_button_url',
            'label'         => 'Bottom CTA Button URL',
            'name'          => 'industries_bottom_cta_button_url',
            'type'          => 'url',
            'default_value' => '/contact',
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_template',
        'operator' => '==',
        'value'    => 'page-industries.php',
    ) ) ),
    'menu_order' => 10,
    'active'     => true,
) );

// ── CONTACT PAGE ───────────────────────────────────────────────────────────────
acf_add_local_field_group( array(
    'key'    => 'group_contact',
    'title'  => 'Contact Page Fields',
    'fields' => array(
        array(
            'key'           => 'field_contact_hero_headline',
            'label'         => 'Hero Headline',
            'name'          => 'contact_hero_headline',
            'type'          => 'text',
            'default_value' => 'Let\'s Build Your Unified Growth Engine',
        ),
        array(
            'key'           => 'field_contact_hero_subheadline',
            'label'         => 'Hero Subheadline',
            'name'          => 'contact_hero_subheadline',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'No pitch decks. No canned proposals. Tell us about your situation and we\'ll have an honest conversation about what growth actually looks like for you.',
        ),
        array(
            'key'           => 'field_contact_email',
            'label'         => 'Contact Email',
            'name'          => 'contact_email',
            'type'          => 'text',
            'default_value' => 'hello@bluuhq.com',
        ),
        array(
            'key'           => 'field_contact_phone',
            'label'         => 'Contact Phone',
            'name'          => 'contact_phone',
            'type'          => 'text',
            'default_value' => '',
        ),
        array(
            'key'           => 'field_contact_location',
            'label'         => 'Location',
            'name'          => 'contact_location',
            'type'          => 'text',
            'default_value' => 'Remote-first, serving North America',
        ),
        array(
            'key'           => 'field_contact_form_headline',
            'label'         => 'Form Headline',
            'name'          => 'contact_form_headline',
            'type'          => 'text',
            'default_value' => 'Start the Conversation',
        ),
        array(
            'key'        => 'field_contact_process',
            'label'      => 'Process Steps',
            'name'       => 'contact_process',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 5,
            'layout'     => 'block',
            'sub_fields' => array(
                array(
                    'key'           => 'field_process_step_number',
                    'label'         => 'Step Number',
                    'name'          => 'step_number',
                    'type'          => 'text',
                    'default_value' => '01',
                ),
                array(
                    'key'           => 'field_process_step_title',
                    'label'         => 'Step Title',
                    'name'          => 'step_title',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_process_step_description',
                    'label'         => 'Step Description',
                    'name'          => 'step_description',
                    'type'          => 'textarea',
                    'rows'          => 3,
                    'default_value' => '',
                ),
            ),
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_template',
        'operator' => '==',
        'value'    => 'page-contact.php',
    ) ) ),
    'menu_order' => 10,
    'active'     => true,
) );
