<?php
/**
 * ACF Local Field Groups
 * Registers all ACF field groups programmatically so they work without the DB.
 *
 * @package bluu-interactive
 */

defined( 'ABSPATH' ) || exit;

if ( ! function_exists( 'acf_add_local_field_group' ) ) {
    return;
}

// ── HOME PAGE ──────────────────────────────────────────────────────────────────
acf_add_local_field_group( array(
    'key'      => 'group_home_hero',
    'title'    => 'Home: Hero Section',
    'fields'   => array(
        array(
            'key'           => 'field_hero_badge',
            'label'         => 'Badge Text',
            'name'          => 'hero_badge',
            'type'          => 'text',
            'default_value' => 'Anti-Fragmentation Agency',
        ),
        array(
            'key'           => 'field_hero_headline',
            'label'         => 'Headline',
            'name'          => 'hero_headline',
            'type'          => 'text',
            'default_value' => 'Stop Managing Vendors. Start Closing Revenue.',
        ),
        array(
            'key'           => 'field_hero_subheadline',
            'label'         => 'Subheadline',
            'name'          => 'hero_subheadline',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Bluu Interactive replaces your web developer, SEO agency, and sales content team with one synchronized engine that drives traffic, converts leads, and closes deals.',
        ),
        array(
            'key'           => 'field_hero_cta_primary_text',
            'label'         => 'Primary CTA Text',
            'name'          => 'hero_cta_primary_text',
            'type'          => 'text',
            'default_value' => 'Book a Discovery Call',
        ),
        array(
            'key'           => 'field_hero_cta_primary_url',
            'label'         => 'Primary CTA URL',
            'name'          => 'hero_cta_primary_url',
            'type'          => 'url',
            'default_value' => '/contact',
        ),
        array(
            'key'           => 'field_hero_cta_secondary_text',
            'label'         => 'Secondary CTA Text',
            'name'          => 'hero_cta_secondary_text',
            'type'          => 'text',
            'default_value' => 'See How It Works',
        ),
        array(
            'key'           => 'field_hero_cta_secondary_url',
            'label'         => 'Secondary CTA URL',
            'name'          => 'hero_cta_secondary_url',
            'type'          => 'url',
            'default_value' => '#pillars',
        ),
        array(
            'key'        => 'field_hero_stats',
            'label'      => 'Stats',
            'name'       => 'hero_stats',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 6,
            'layout'     => 'table',
            'sub_fields' => array(
                array(
                    'key'           => 'field_hero_stat_number',
                    'label'         => 'Number',
                    'name'          => 'stat_number',
                    'type'          => 'text',
                    'default_value' => '',
                    'column_width'  => '',
                ),
                array(
                    'key'           => 'field_hero_stat_label',
                    'label'         => 'Label',
                    'name'          => 'stat_label',
                    'type'          => 'text',
                    'default_value' => '',
                    'column_width'  => '',
                ),
            ),
        ),
        array(
            'key'           => 'field_hero_image',
            'label'         => 'Hero Image',
            'name'          => 'hero_image',
            'type'          => 'image',
            'return_format' => 'array',
            'preview_size'  => 'medium',
            'library'       => 'all',
            'instructions'  => 'Right-hand image in the hero section. Recommended size: 900×675px (4:3). If left empty a default image is used.',
        ),
    ),
    'location' => array(
        array( array( 'param' => 'page_type',     'operator' => '==', 'value' => 'front_page' ) ),
        array( array( 'param' => 'page_template', 'operator' => '==', 'value' => 'front-page.php' ) ),
    ),
    'menu_order'            => 10,
    'position'              => 'normal',
    'style'                 => 'default',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'active'                => true,
) );

acf_add_local_field_group( array(
    'key'    => 'group_home_problem',
    'title'  => 'Home: Problem Section',
    'fields' => array(
        array(
            'key'           => 'field_problem_badge',
            'label'         => 'Badge',
            'name'          => 'problem_badge',
            'type'          => 'text',
            'default_value' => 'The Problem',
        ),
        array(
            'key'           => 'field_problem_headline',
            'label'         => 'Headline',
            'name'          => 'problem_headline',
            'type'          => 'text',
            'default_value' => 'Fragmentation Is Costing You Revenue',
        ),
        array(
            'key'           => 'field_problem_body',
            'label'         => 'Body',
            'name'          => 'problem_body',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Most B2B companies are paying 3–5 vendors who never talk to each other. The result: misaligned messaging, stalled pipeline, and a digital presence that doesn\'t convert.',
        ),
        array(
            'key'        => 'field_problem_items',
            'label'      => 'Problem Items',
            'name'       => 'problem_items',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 6,
            'layout'     => 'block',
            'sub_fields' => array(
                array(
                    'key'           => 'field_problem_item_icon',
                    'label'         => 'Icon (SVG name)',
                    'name'          => 'icon',
                    'type'          => 'text',
                    'default_value' => 'x-circle',
                ),
                array(
                    'key'           => 'field_problem_item_title',
                    'label'         => 'Title',
                    'name'          => 'title',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_problem_item_description',
                    'label'         => 'Description',
                    'name'          => 'description',
                    'type'          => 'textarea',
                    'rows'          => 3,
                    'default_value' => '',
                ),
            ),
        ),
    ),
    'location'   => array(
        array( array( 'param' => 'page_type',     'operator' => '==', 'value' => 'front_page' ) ),
        array( array( 'param' => 'page_template', 'operator' => '==', 'value' => 'front-page.php' ) ),
    ),
    'menu_order' => 20,
    'active'     => true,
) );

acf_add_local_field_group( array(
    'key'    => 'group_home_solution',
    'title'  => 'Home: Solution / Pillars Section',
    'fields' => array(
        array(
            'key'           => 'field_solution_badge',
            'label'         => 'Solution Badge',
            'name'          => 'solution_badge',
            'type'          => 'text',
            'default_value' => 'The Solution',
        ),
        array(
            'key'           => 'field_solution_headline',
            'label'         => 'Solution Headline',
            'name'          => 'solution_headline',
            'type'          => 'text',
            'default_value' => 'One Team. Three Engines. Total Growth.',
        ),
        array(
            'key'           => 'field_solution_body',
            'label'         => 'Solution Body',
            'name'          => 'solution_body',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Bluu Interactive unifies web infrastructure, authority content, and sales assets under one synchronized strategy — so every touchpoint works together.',
        ),
        array(
            'key'        => 'field_pillars',
            'label'      => 'Pillars',
            'name'       => 'pillars',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 3,
            'layout'     => 'block',
            'sub_fields' => array(
                array(
                    'key'           => 'field_pillar_icon',
                    'label'         => 'Icon Name',
                    'name'          => 'pillar_icon',
                    'type'          => 'text',
                    'default_value' => 'server',
                ),
                array(
                    'key'           => 'field_pillar_label',
                    'label'         => 'Label Chip',
                    'name'          => 'pillar_label',
                    'type'          => 'text',
                    'default_value' => 'Pillar 1',
                ),
                array(
                    'key'           => 'field_pillar_title',
                    'label'         => 'Title',
                    'name'          => 'pillar_title',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_pillar_description',
                    'label'         => 'Description',
                    'name'          => 'pillar_description',
                    'type'          => 'textarea',
                    'rows'          => 3,
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_pillar_feature_1',
                    'label'         => 'Feature 1',
                    'name'          => 'pillar_feature_1',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_pillar_feature_2',
                    'label'         => 'Feature 2',
                    'name'          => 'pillar_feature_2',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_pillar_feature_3',
                    'label'         => 'Feature 3',
                    'name'          => 'pillar_feature_3',
                    'type'          => 'text',
                    'default_value' => '',
                ),
            ),
        ),
    ),
    'location'   => array(
        array( array( 'param' => 'page_type',     'operator' => '==', 'value' => 'front_page' ) ),
        array( array( 'param' => 'page_template', 'operator' => '==', 'value' => 'front-page.php' ) ),
    ),
    'menu_order' => 30,
    'active'     => true,
) );

acf_add_local_field_group( array(
    'key'    => 'group_home_icp',
    'title'  => 'Home: ICP / Who We Serve Section',
    'fields' => array(
        array(
            'key'           => 'field_icp_badge',
            'label'         => 'Badge',
            'name'          => 'icp_badge',
            'type'          => 'text',
            'default_value' => 'Who We Serve',
        ),
        array(
            'key'           => 'field_icp_headline',
            'label'         => 'Headline',
            'name'          => 'icp_headline',
            'type'          => 'text',
            'default_value' => 'Built for $2M–$50M B2B Companies',
        ),
        array(
            'key'           => 'field_icp_body',
            'label'         => 'Body',
            'name'          => 'icp_body',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'We focus exclusively on industries where expertise, trust, and precision are non-negotiable. If your buyers demand authority, we\'re built for you.',
        ),
        array(
            'key'        => 'field_icp_verticals',
            'label'      => 'Verticals',
            'name'       => 'icp_verticals',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 8,
            'layout'     => 'block',
            'sub_fields' => array(
                array(
                    'key'           => 'field_icp_vertical_icon',
                    'label'         => 'Icon',
                    'name'          => 'icon',
                    'type'          => 'text',
                    'default_value' => 'briefcase',
                ),
                array(
                    'key'           => 'field_icp_vertical_title',
                    'label'         => 'Title',
                    'name'          => 'title',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_icp_vertical_description',
                    'label'         => 'Description',
                    'name'          => 'description',
                    'type'          => 'textarea',
                    'rows'          => 3,
                    'default_value' => '',
                ),
            ),
        ),
        array(
            'key'           => 'field_home_cta_headline',
            'label'         => 'CTA Headline',
            'name'          => 'home_cta_headline',
            'type'          => 'text',
            'default_value' => 'Ready to Replace Fragmentation With Growth?',
        ),
        array(
            'key'           => 'field_home_cta_body',
            'label'         => 'CTA Body',
            'name'          => 'home_cta_body',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Book a 30-minute Discovery Call. No pitch. Just an honest conversation about your current stack and where the gaps are.',
        ),
        array(
            'key'           => 'field_home_cta_button_text',
            'label'         => 'CTA Button Text',
            'name'          => 'home_cta_button_text',
            'type'          => 'text',
            'default_value' => 'Book a Discovery Call',
        ),
        array(
            'key'           => 'field_home_cta_button_url',
            'label'         => 'CTA Button URL',
            'name'          => 'home_cta_button_url',
            'type'          => 'url',
            'default_value' => '/contact',
        ),
    ),
    'location'   => array(
        array( array( 'param' => 'page_type',     'operator' => '==', 'value' => 'front_page' ) ),
        array( array( 'param' => 'page_template', 'operator' => '==', 'value' => 'front-page.php' ) ),
    ),
    'menu_order' => 40,
    'active'     => true,
) );

// ── PRICING PAGE ───────────────────────────────────────────────────────────────
acf_add_local_field_group( array(
    'key'    => 'group_pricing',
    'title'  => 'Pricing Page Fields',
    'fields' => array(
        array(
            'key'           => 'field_pricing_hero_headline',
            'label'         => 'Hero Headline',
            'name'          => 'pricing_hero_headline',
            'type'          => 'text',
            'default_value' => 'Transparent, All-Inclusive Pricing',
        ),
        array(
            'key'           => 'field_pricing_hero_subheadline',
            'label'         => 'Hero Subheadline',
            'name'          => 'pricing_hero_subheadline',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'No retainer games. No surprise invoices. One subscription that covers everything your growth engine needs.',
        ),
        array(
            'key'        => 'field_pricing_tiers',
            'label'      => 'Pricing Tiers',
            'name'       => 'pricing_tiers',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 5,
            'layout'     => 'block',
            'sub_fields' => array(
                array(
                    'key'           => 'field_tier_badge',
                    'label'         => 'Badge',
                    'name'          => 'tier_badge',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_tier_name',
                    'label'         => 'Tier Name',
                    'name'          => 'tier_name',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_tier_price',
                    'label'         => 'Price',
                    'name'          => 'tier_price',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_tier_price_suffix',
                    'label'         => 'Price Suffix',
                    'name'          => 'tier_price_suffix',
                    'type'          => 'text',
                    'default_value' => '/month',
                ),
                array(
                    'key'           => 'field_tier_tagline',
                    'label'         => 'Tagline',
                    'name'          => 'tier_tagline',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_tier_features',
                    'label'         => 'Features (one per line)',
                    'name'          => 'tier_features',
                    'type'          => 'textarea',
                    'rows'          => 6,
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_tier_cta_text',
                    'label'         => 'CTA Text',
                    'name'          => 'tier_cta_text',
                    'type'          => 'text',
                    'default_value' => 'Get Started',
                ),
                array(
                    'key'           => 'field_tier_cta_url',
                    'label'         => 'CTA URL',
                    'name'          => 'tier_cta_url',
                    'type'          => 'url',
                    'default_value' => '/contact',
                ),
                array(
                    'key'           => 'field_tier_is_featured',
                    'label'         => 'Is Featured (Most Popular)?',
                    'name'          => 'tier_is_featured',
                    'type'          => 'true_false',
                    'default_value' => 0,
                ),
                array(
                    'key'           => 'field_tier_note',
                    'label'         => 'Footer Note',
                    'name'          => 'tier_note',
                    'type'          => 'text',
                    'default_value' => '',
                ),
            ),
        ),
        array(
            'key'        => 'field_pricing_faq',
            'label'      => 'FAQ Items',
            'name'       => 'pricing_faq',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 20,
            'layout'     => 'block',
            'sub_fields' => array(
                array(
                    'key'           => 'field_faq_question',
                    'label'         => 'Question',
                    'name'          => 'question',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_faq_answer',
                    'label'         => 'Answer',
                    'name'          => 'answer',
                    'type'          => 'textarea',
                    'rows'          => 4,
                    'default_value' => '',
                ),
            ),
        ),
        array(
            'key'           => 'field_pricing_bottom_cta_headline',
            'label'         => 'Bottom CTA Headline',
            'name'          => 'pricing_bottom_cta_headline',
            'type'          => 'text',
            'default_value' => 'Not Sure Which Plan Fits?',
        ),
        array(
            'key'           => 'field_pricing_bottom_cta_body',
            'label'         => 'Bottom CTA Body',
            'name'          => 'pricing_bottom_cta_body',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Let\'s talk. A 30-minute Discovery Call is free and commitment-free. We\'ll tell you exactly which plan — if any — makes sense for your stage.',
        ),
        array(
            'key'           => 'field_pricing_bottom_cta_button_text',
            'label'         => 'Bottom CTA Button Text',
            'name'          => 'pricing_bottom_cta_button_text',
            'type'          => 'text',
            'default_value' => 'Book a Discovery Call',
        ),
        array(
            'key'           => 'field_pricing_bottom_cta_button_url',
            'label'         => 'Bottom CTA Button URL',
            'name'          => 'pricing_bottom_cta_button_url',
            'type'          => 'url',
            'default_value' => '/contact',
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_template',
        'operator' => '==',
        'value'    => 'page-pricing.php',
    ) ) ),
    'menu_order' => 10,
    'active'     => true,
) );

// ── INDUSTRIES PAGE ────────────────────────────────────────────────────────────
acf_add_local_field_group( array(
    'key'    => 'group_industries',
    'title'  => 'Industries Page Fields',
    'fields' => array(
        array(
            'key'           => 'field_industries_hero_headline',
            'label'         => 'Hero Headline',
            'name'          => 'industries_hero_headline',
            'type'          => 'text',
            'default_value' => 'Built for Industries Where Trust Is Non-Negotiable',
        ),
        array(
            'key'           => 'field_industries_hero_subheadline',
            'label'         => 'Hero Subheadline',
            'name'          => 'industries_hero_subheadline',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'We don\'t work in every industry. We go deep in four — where our expertise creates an unfair competitive advantage for our clients.',
        ),
        array(
            'key'        => 'field_industries',
            'label'      => 'Industries',
            'name'       => 'industries',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 8,
            'layout'     => 'block',
            'sub_fields' => array(
                array(
                    'key'           => 'field_industry_icon',
                    'label'         => 'Icon',
                    'name'          => 'industry_icon',
                    'type'          => 'text',
                    'default_value' => 'briefcase',
                ),
                array(
                    'key'           => 'field_industry_name',
                    'label'         => 'Industry Name',
                    'name'          => 'industry_name',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_industry_tagline',
                    'label'         => 'Tagline',
                    'name'          => 'industry_tagline',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_industry_challenge',
                    'label'         => 'Challenge',
                    'name'          => 'industry_challenge',
                    'type'          => 'textarea',
                    'rows'          => 3,
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_industry_solution',
                    'label'         => 'Solution',
                    'name'          => 'industry_solution',
                    'type'          => 'textarea',
                    'rows'          => 3,
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_industry_stat_number',
                    'label'         => 'Stat Number',
                    'name'          => 'industry_stat_number',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_industry_stat_label',
                    'label'         => 'Stat Label',
                    'name'          => 'industry_stat_label',
                    'type'          => 'text',
                    'default_value' => '',
                ),
            ),
        ),
        array(
            'key'           => 'field_industries_bottom_cta_headline',
            'label'         => 'Bottom CTA Headline',
            'name'          => 'industries_bottom_cta_headline',
            'type'          => 'text',
            'default_value' => 'Your Industry. Your Rules. Our Engine.',
        ),
        array(
            'key'           => 'field_industries_bottom_cta_body',
            'label'         => 'Bottom CTA Body',
            'name'          => 'industries_bottom_cta_body',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'We only take on clients we know we can win for. Let\'s find out if we\'re the right fit.',
        ),
        array(
            'key'           => 'field_industries_bottom_cta_button_text',
            'label'         => 'Bottom CTA Button Text',
            'name'          => 'industries_bottom_cta_button_text',
            'type'          => 'text',
            'default_value' => 'Book a Discovery Call',
        ),
        array(
            'key'           => 'field_industries_bottom_cta_button_url',
            'label'         => 'Bottom CTA Button URL',
            'name'          => 'industries_bottom_cta_button_url',
            'type'          => 'url',
            'default_value' => '/contact',
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_template',
        'operator' => '==',
        'value'    => 'page-industries.php',
    ) ) ),
    'menu_order' => 10,
    'active'     => true,
) );

// ── CONTACT PAGE ───────────────────────────────────────────────────────────────
acf_add_local_field_group( array(
    'key'    => 'group_contact',
    'title'  => 'Contact Page Fields',
    'fields' => array(
        array(
            'key'           => 'field_contact_hero_headline',
            'label'         => 'Hero Headline',
            'name'          => 'contact_hero_headline',
            'type'          => 'text',
            'default_value' => 'Let\'s Build Your Unified Growth Engine',
        ),
        array(
            'key'           => 'field_contact_hero_subheadline',
            'label'         => 'Hero Subheadline',
            'name'          => 'contact_hero_subheadline',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'No pitch decks. No canned proposals. Tell us about your situation and we\'ll have an honest conversation about what growth actually looks like for you.',
        ),
        array(
            'key'           => 'field_contact_email',
            'label'         => 'Contact Email',
            'name'          => 'contact_email',
            'type'          => 'text',
            'default_value' => 'hello@bluuhq.com',
        ),
        array(
            'key'           => 'field_contact_phone',
            'label'         => 'Contact Phone',
            'name'          => 'contact_phone',
            'type'          => 'text',
            'default_value' => '',
        ),
        array(
            'key'           => 'field_contact_location',
            'label'         => 'Location',
            'name'          => 'contact_location',
            'type'          => 'text',
            'default_value' => 'Remote-first, serving North America',
        ),
        array(
            'key'           => 'field_contact_form_headline',
            'label'         => 'Form Headline',
            'name'          => 'contact_form_headline',
            'type'          => 'text',
            'default_value' => 'Start the Conversation',
        ),
        array(
            'key'        => 'field_contact_process',
            'label'      => 'Process Steps',
            'name'       => 'contact_process',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 5,
            'layout'     => 'block',
            'sub_fields' => array(
                array(
                    'key'           => 'field_process_step_number',
                    'label'         => 'Step Number',
                    'name'          => 'step_number',
                    'type'          => 'text',
                    'default_value' => '01',
                ),
                array(
                    'key'           => 'field_process_step_title',
                    'label'         => 'Step Title',
                    'name'          => 'step_title',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_process_step_description',
                    'label'         => 'Step Description',
                    'name'          => 'step_description',
                    'type'          => 'textarea',
                    'rows'          => 3,
                    'default_value' => '',
                ),
            ),
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_template',
        'operator' => '==',
        'value'    => 'page-contact.php',
    ) ) ),
    'menu_order' => 10,
    'active'     => true,
) );

// ── FAQ PAGE ───────────────────────────────────────────────────────────────────
acf_add_local_field_group( array(
    'key'    => 'group_faq_page',
    'title'  => 'FAQ Page',
    'fields' => array(

        // Hero
        array(
            'key'           => 'field_faq_headline',
            'label'         => 'Page Headline',
            'name'          => 'faq_headline',
            'type'          => 'text',
            'default_value' => 'Everything You Need to Know',
        ),
        array(
            'key'           => 'field_faq_subheadline',
            'label'         => 'Page Subheadline',
            'name'          => 'faq_subheadline',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => 'Straight answers about how Bluu Interactive works, what we cost, and what you can expect.',
        ),

        // FAQ Categories (repeater → sub-repeater)
        array(
            'key'        => 'field_faq_categories',
            'label'      => 'FAQ Categories',
            'name'       => 'faq_categories',
            'type'       => 'repeater',
            'min'        => 1,
            'layout'     => 'block',
            'button_label' => 'Add Category',
            'sub_fields' => array(

                array(
                    'key'           => 'field_faq_cat_name',
                    'label'         => 'Category Name',
                    'name'          => 'category_name',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_faq_cat_desc',
                    'label'         => 'Category Description (optional)',
                    'name'          => 'category_description',
                    'type'          => 'text',
                    'default_value' => '',
                ),
                array(
                    'key'           => 'field_faq_cat_icon',
                    'label'         => 'Category Icon',
                    'name'          => 'category_icon',
                    'type'          => 'select',
                    'choices'       => array(
                        'info'    => 'General / Info',
                        'pricing' => 'Pricing',
                        'content' => 'Content',
                        'tech'    => 'Technology',
                        'start'   => 'Getting Started',
                        'default' => 'Default (Question mark)',
                    ),
                    'default_value' => 'default',
                ),

                // Nested repeater: FAQ items within each category
                array(
                    'key'          => 'field_faq_items',
                    'label'        => 'Questions & Answers',
                    'name'         => 'faq_items',
                    'type'         => 'repeater',
                    'min'          => 1,
                    'layout'       => 'row',
                    'button_label' => 'Add Question',
                    'sub_fields'   => array(
                        array(
                            'key'           => 'field_faq_question',
                            'label'         => 'Question',
                            'name'          => 'question',
                            'type'          => 'text',
                            'default_value' => '',
                        ),
                        array(
                            'key'           => 'field_faq_answer',
                            'label'         => 'Answer',
                            'name'          => 'answer',
                            'type'          => 'textarea',
                            'rows'          => 5,
                            'default_value' => '',
                            'instructions'  => 'Supports line breaks. Use **bold** notation — it will be rendered as bold text.',
                        ),
                    ),
                ),
            ),
        ),

        // Bottom CTA
        array(
            'key'           => 'field_faq_cta_headline',
            'label'         => 'CTA Headline',
            'name'          => 'faq_cta_headline',
            'type'          => 'text',
            'default_value' => 'Still Have Questions?',
        ),
        array(
            'key'           => 'field_faq_cta_body',
            'label'         => 'CTA Body',
            'name'          => 'faq_cta_body',
            'type'          => 'textarea',
            'rows'          => 2,
            'default_value' => "We'd rather talk than leave you guessing. Book a no-pressure, 30-minute discovery call and we'll answer everything specific to your situation.",
        ),
        array(
            'key'           => 'field_faq_cta_button_text',
            'label'         => 'CTA Button Text',
            'name'          => 'faq_cta_button_text',
            'type'          => 'text',
            'default_value' => 'Book a Discovery Call',
        ),
        array(
            'key'  => 'field_faq_cta_button_url',
            'label' => 'CTA Button URL',
            'name'  => 'faq_cta_button_url',
            'type'  => 'url',
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_template',
        'operator' => '==',
        'value'    => 'page-faq.php',
    ) ) ),
    'menu_order' => 10,
    'active'     => true,
) );

// ── USE CASE PAGE TEMPLATE ─────────────────────────────────────────────────────

// Group 1 — Page meta & hero
acf_add_local_field_group( array(
    'key'    => 'group_uc_hero',
    'title'  => 'Use Case: Page Meta & Hero',
    'fields' => array(
        array(
            'key'     => 'field_uc_industry',
            'label'   => 'Industry',
            'name'    => 'uc_industry',
            'type'    => 'select',
            'choices' => array(
                'tech-saas'              => 'Tech & SaaS',
                'agencies-consultants'   => 'Agencies & Consultants',
                'ecommerce-dtc'          => 'E-commerce & DTC',
                'professional-services'  => 'Professional Services',
            ),
            'allow_null'    => 0,
            'multiple'      => 0,
            'return_format' => 'value',
        ),
        array(
            'key'           => 'field_uc_seo_title',
            'label'         => 'SEO Page Title',
            'name'          => 'uc_seo_title',
            'type'          => 'text',
            'maxlength'     => 60,
            'instructions'  => 'Used in the <title> tag. Different from the hero headline.',
        ),
        array(
            'key'          => 'field_uc_meta_description',
            'label'        => 'Meta Description',
            'name'         => 'uc_meta_description',
            'type'         => 'textarea',
            'maxlength'    => 155,
            'rows'         => 3,
            'instructions' => 'Meta description for search engines.',
        ),
        array(
            'key'          => 'field_uc_hero_tag',
            'label'        => 'Hero Tag',
            'name'         => 'uc_hero_tag',
            'type'         => 'text',
            'maxlength'    => 40,
            'instructions' => 'Small label above the headline. E.g. "Use case — Tech & SaaS"',
        ),
        array(
            'key'          => 'field_uc_hero_headline',
            'label'        => 'Hero Headline',
            'name'         => 'uc_hero_headline',
            'type'         => 'text',
            'maxlength'    => 80,
            'instructions' => 'Main H1 headline. Outcome-led. Sentence case.',
        ),
        array(
            'key'          => 'field_uc_hero_subheadline',
            'label'        => 'Hero Subheadline',
            'name'         => 'uc_hero_subheadline',
            'type'         => 'textarea',
            'maxlength'    => 180,
            'rows'         => 3,
            'instructions' => '1–2 sentences below the headline. Plain language, no jargon.',
        ),
        array(
            'key'           => 'field_uc_hero_cta_label',
            'label'         => 'Primary CTA Label',
            'name'          => 'uc_hero_cta_label',
            'type'          => 'text',
            'maxlength'     => 40,
            'default_value' => 'Book a Discovery Call',
        ),
        array(
            'key'           => 'field_uc_hero_cta_url',
            'label'         => 'Primary CTA URL',
            'name'          => 'uc_hero_cta_url',
            'type'          => 'url',
            'default_value' => '/contact',
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_template',
        'operator' => '==',
        'value'    => 'page-use-case.php',
    ) ) ),
    'menu_order' => 10,
    'active'     => true,
) );

// Group 2 — The situation
acf_add_local_field_group( array(
    'key'    => 'group_uc_situation',
    'title'  => 'Use Case: The Situation',
    'fields' => array(
        array(
            'key'          => 'field_uc_situation_heading',
            'label'        => 'Section Heading',
            'name'         => 'uc_situation_heading',
            'type'         => 'text',
            'maxlength'    => 60,
            'default_value' => 'The situation',
        ),
        array(
            'key'          => 'field_uc_situation_body',
            'label'        => 'Section Body',
            'name'         => 'uc_situation_body',
            'type'         => 'textarea',
            'maxlength'    => 400,
            'rows'         => 4,
            'instructions' => '2–3 sentences describing the specific pain this use case addresses. Written for the reader, not about them.',
        ),
        array(
            'key'          => 'field_uc_situation_pain_points',
            'label'        => 'Pain Points',
            'name'         => 'uc_situation_pain_points',
            'type'         => 'repeater',
            'min'          => 3,
            'max'          => 3,
            'layout'       => 'block',
            'button_label' => 'Add pain point',
            'sub_fields'   => array(
                array(
                    'key'       => 'field_uc_pain_title',
                    'label'     => 'Title',
                    'name'      => 'uc_pain_title',
                    'type'      => 'text',
                    'maxlength' => 50,
                ),
                array(
                    'key'       => 'field_uc_pain_body',
                    'label'     => 'Body',
                    'name'      => 'uc_pain_body',
                    'type'      => 'textarea',
                    'maxlength' => 120,
                    'rows'      => 2,
                ),
            ),
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_template',
        'operator' => '==',
        'value'    => 'page-use-case.php',
    ) ) ),
    'menu_order' => 20,
    'active'     => true,
) );

// Group 3 — The approach
acf_add_local_field_group( array(
    'key'    => 'group_uc_approach',
    'title'  => 'Use Case: The Approach',
    'fields' => array(
        array(
            'key'           => 'field_uc_approach_heading',
            'label'         => 'Section Heading',
            'name'          => 'uc_approach_heading',
            'type'          => 'text',
            'maxlength'     => 60,
            'default_value' => 'How Bluu approaches this',
        ),
        array(
            'key'          => 'field_uc_approach_body',
            'label'        => 'Section Body',
            'name'         => 'uc_approach_body',
            'type'         => 'textarea',
            'maxlength'    => 400,
            'rows'         => 4,
            'instructions' => "2–3 sentences explaining Bluu's method for this use case. Specific, not generic.",
        ),
        array(
            'key'          => 'field_uc_approach_steps',
            'label'        => 'Steps',
            'name'         => 'uc_approach_steps',
            'type'         => 'repeater',
            'min'          => 3,
            'max'          => 4,
            'layout'       => 'block',
            'button_label' => 'Add step',
            'sub_fields'   => array(
                array(
                    'key'   => 'field_uc_step_number',
                    'label' => 'Step Number',
                    'name'  => 'uc_step_number',
                    'type'  => 'text',
                ),
                array(
                    'key'       => 'field_uc_step_title',
                    'label'     => 'Step Title',
                    'name'      => 'uc_step_title',
                    'type'      => 'text',
                    'maxlength' => 50,
                ),
                array(
                    'key'       => 'field_uc_step_body',
                    'label'     => 'Step Body',
                    'name'      => 'uc_step_body',
                    'type'      => 'textarea',
                    'maxlength' => 140,
                    'rows'      => 2,
                ),
            ),
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_template',
        'operator' => '==',
        'value'    => 'page-use-case.php',
    ) ) ),
    'menu_order' => 30,
    'active'     => true,
) );

// Group 4 — What you get
acf_add_local_field_group( array(
    'key'    => 'group_uc_deliverables',
    'title'  => 'Use Case: What You Get',
    'fields' => array(
        array(
            'key'           => 'field_uc_deliverables_heading',
            'label'         => 'Section Heading',
            'name'          => 'uc_deliverables_heading',
            'type'          => 'text',
            'maxlength'     => 60,
            'default_value' => 'What you receive',
        ),
        array(
            'key'          => 'field_uc_deliverables_intro',
            'label'        => 'Intro Sentence',
            'name'         => 'uc_deliverables_intro',
            'type'         => 'textarea',
            'maxlength'    => 200,
            'rows'         => 2,
            'instructions' => 'One sentence framing the deliverables list.',
        ),
        array(
            'key'          => 'field_uc_deliverables_list',
            'label'        => 'Deliverables',
            'name'         => 'uc_deliverables_list',
            'type'         => 'repeater',
            'min'          => 4,
            'max'          => 6,
            'layout'       => 'block',
            'button_label' => 'Add deliverable',
            'sub_fields'   => array(
                array(
                    'key'       => 'field_uc_deliverable_name',
                    'label'     => 'Deliverable Name',
                    'name'      => 'uc_deliverable_name',
                    'type'      => 'text',
                    'maxlength' => 60,
                ),
                array(
                    'key'       => 'field_uc_deliverable_detail',
                    'label'     => 'Detail',
                    'name'      => 'uc_deliverable_detail',
                    'type'      => 'textarea',
                    'maxlength' => 120,
                    'rows'      => 2,
                ),
            ),
        ),
        array(
            'key'          => 'field_uc_cadence',
            'label'        => 'Cadence Note',
            'name'         => 'uc_cadence',
            'type'         => 'text',
            'maxlength'    => 80,
            'default_value' => 'Delivered weekly as part of your retainer.',
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_template',
        'operator' => '==',
        'value'    => 'page-use-case.php',
    ) ) ),
    'menu_order' => 40,
    'active'     => true,
) );

// Group 5 — Who this is for
acf_add_local_field_group( array(
    'key'    => 'group_uc_fit',
    'title'  => 'Use Case: Who This Is For',
    'fields' => array(
        array(
            'key'           => 'field_uc_fit_heading',
            'label'         => 'Section Heading',
            'name'          => 'uc_fit_heading',
            'type'          => 'text',
            'maxlength'     => 60,
            'default_value' => 'Who this is right for',
        ),
        array(
            'key'          => 'field_uc_fit_list',
            'label'        => 'Fit Statements',
            'name'         => 'uc_fit_list',
            'type'         => 'repeater',
            'min'          => 3,
            'max'          => 4,
            'layout'       => 'block',
            'button_label' => 'Add fit statement',
            'instructions' => 'Each statement should start with "You are..." or "You have..."',
            'sub_fields'   => array(
                array(
                    'key'       => 'field_uc_fit_statement',
                    'label'     => 'Statement',
                    'name'      => 'uc_fit_statement',
                    'type'      => 'textarea',
                    'maxlength' => 120,
                    'rows'      => 2,
                ),
            ),
        ),
        array(
            'key'          => 'field_uc_not_fit_note',
            'label'        => 'Not a Fit Note',
            'name'         => 'uc_not_fit_note',
            'type'         => 'textarea',
            'maxlength'    => 180,
            'rows'         => 2,
            'instructions' => 'Optional. One honest sentence about who this is NOT right for. Builds trust.',
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_template',
        'operator' => '==',
        'value'    => 'page-use-case.php',
    ) ) ),
    'menu_order' => 50,
    'active'     => true,
) );

// Group 6 — Related use cases
acf_add_local_field_group( array(
    'key'    => 'group_uc_related',
    'title'  => 'Use Case: Related Use Cases',
    'fields' => array(
        array(
            'key'          => 'field_uc_related_pages',
            'label'        => 'Related Pages',
            'name'         => 'uc_related_pages',
            'type'         => 'repeater',
            'min'          => 2,
            'max'          => 3,
            'layout'       => 'block',
            'button_label' => 'Add related page',
            'sub_fields'   => array(
                array(
                    'key'   => 'field_uc_related_title',
                    'label' => 'Title',
                    'name'  => 'uc_related_title',
                    'type'  => 'text',
                ),
                array(
                    'key'   => 'field_uc_related_url',
                    'label' => 'URL',
                    'name'  => 'uc_related_url',
                    'type'  => 'url',
                ),
                array(
                    'key'       => 'field_uc_related_description',
                    'label'     => 'Description',
                    'name'      => 'uc_related_description',
                    'type'      => 'textarea',
                    'maxlength' => 100,
                    'rows'      => 2,
                ),
            ),
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_template',
        'operator' => '==',
        'value'    => 'page-use-case.php',
    ) ) ),
    'menu_order' => 60,
    'active'     => true,
) );

// Group 7 — Closing CTA
acf_add_local_field_group( array(
    'key'    => 'group_uc_cta',
    'title'  => 'Use Case: Closing CTA',
    'fields' => array(
        array(
            'key'          => 'field_uc_cta_heading',
            'label'        => 'CTA Heading',
            'name'         => 'uc_cta_heading',
            'type'         => 'text',
            'maxlength'    => 80,
            'instructions' => 'Closing CTA headline. Specific to this use case, not generic.',
        ),
        array(
            'key'          => 'field_uc_cta_subtext',
            'label'        => 'CTA Subtext',
            'name'         => 'uc_cta_subtext',
            'type'         => 'textarea',
            'maxlength'    => 200,
            'rows'         => 3,
            'instructions' => '1–2 sentences. Low pressure. References the Discovery Call.',
        ),
        array(
            'key'           => 'field_uc_cta_primary_label',
            'label'         => 'Primary Button Label',
            'name'          => 'uc_cta_primary_label',
            'type'          => 'text',
            'maxlength'     => 40,
            'default_value' => 'Book a Discovery Call',
        ),
        array(
            'key'           => 'field_uc_cta_primary_url',
            'label'         => 'Primary Button URL',
            'name'          => 'uc_cta_primary_url',
            'type'          => 'url',
            'default_value' => '/contact',
        ),
        array(
            'key'           => 'field_uc_cta_secondary_label',
            'label'         => 'Secondary Button Label',
            'name'          => 'uc_cta_secondary_label',
            'type'          => 'text',
            'maxlength'     => 40,
            'default_value' => 'See pricing',
        ),
        array(
            'key'           => 'field_uc_cta_secondary_url',
            'label'         => 'Secondary Button URL',
            'name'          => 'uc_cta_secondary_url',
            'type'          => 'url',
            'default_value' => '/pricing',
        ),
    ),
    'location'   => array( array( array(
        'param'    => 'page_template',
        'operator' => '==',
        'value'    => 'page-use-case.php',
    ) ) ),
    'menu_order' => 70,
    'active'     => true,
) );
